### ISSUE TITLE
${revision} not being updated

### ISSUE THREAD

**Issue by fmodesto** [mojohaus/versions#855]
This is a sample pom to illustrate the issue
`
    <project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>test-versions</artifactId>
    <version>${revision}</version>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <revision>1.3</revision>
    </properties>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>versions-maven-plugin</artifactId>
                    <version>2.14.1</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>`

`mvn versions:set -DnewVersion=2.0`

With plugin 2.13.0 it resolves all ${revision} to the new version.
With plugin 2.14.0 and 2.14.1 it does nothing.

**Comment by ajarmoniuk** [comment]
Too bad we're after this hotfix release.

**Comment by slawekjaranowski** [comment]
Why do you use `version:set` at all when you use `ci-friendly` properties? 

Do you also need a task to change pinned version to `${revision}` like:

```
mvn versions:set -DnewVersion=${revision}
```

**Comment by deckrider** [comment]
We use `${revision}-SNAPSHOT` but at official build time, use `versions:set -DnewVersion=1.2.3` so that our version is momentarily hard coded.

Thus we also have this problem.  The workaround seems to be adding `-DoldVersion='*'`

**Comment by lavoiesl** [comment]
> The workaround seems to be adding -DoldVersion='*'

This workaround also worked for me, thanks 🙏🏼

**Comment by hackmann** [comment]
> Why do you use `version:set` at all when you use `ci-friendly` properties?
> 
> Do you also need a task to change pinned version to `${revision}` like:
> 
> ```
> mvn versions:set -DnewVersion=${revision}
> ```

I'm looking into switch from normal versions to these CI friendly versions. I can use shell scripting to add the `revision` property, `mvn versions:set-property` does not create a property if it does not exist already. But was hoping to use `mvn versions:set` to set the version for main pom file and all child modules

**Comment by CharlieReitzel** [comment]
With 2.15.0, when I run `mvn versions:set -DnewVersion=1.2.3 -Dmaven.main.skip -DskipTests=true -DskipUiRebuild=true -Dmaven.install.skip`, the parent and all child projects are overwritten to `<version>1.2.3</version>` and the `revision` property is ignored.   

Adding `-DoldVersion='*'` made no difference.

What am I missing?

Fwiw, I'm using a multi-module project with a CI pipeline that is forcing the `versions:set` on every merge to `main`.  I have no control over the pipeline and the team that does is stretched thin.   So if I can get a project that uses `$revision` to work with `versions:set`, it'll be a big help.

**Comment by deckrider** [comment]
@CharlieReitzel see this scenario:  https://github.com/mojohaus/versions/issues/855#issuecomment-1354732975

**Comment by ajarmoniuk** [comment]
I don't think that the `set` goal will update a property value.

Before version 2.13.0, it did not interpolate properties at all. In versions 2.14.0 and 2.15.0 it made an incomplete attempt at doing it, but I'm now reverting that behaviour.

**Comment by CharlieReitzel** [comment]
> @CharlieReitzel see this scenario: [#855 (comment)](https://github.com/mojohaus/versions/issues/855#issuecomment-1354732975)

That's where I got the idea to try `-DoldVersion='*'`.

So, if I understand it right.  If you use `version:set -DnewVersion=1.2.3` on a project using `<version>${revision}></version>`, you are asking the plugin to drop use of the `revision` property in favor of a fixed version.    Is that the intent?

Should I submit a feature request to support updating the version for projects that use the `$revision` property by simply updating the property value and leaving everything else alone?

**Comment by ajarmoniuk** [comment]
Yes, of course you can request a new feature.

**Comment by CharlieReitzel** [comment]
In our work environment, all projects use shared CI/CD pipeline code that forces a version update with every merge to `main` by calling `mvn versions:set -DnewVersion=1.n.0`, i.e. takes your highest level version number as is, increments  your 2nd level version level by 1 and sets the lowest level version to zero (0).  It figures out the version number on its own.

Because I'm using a multi-module project, I'm using `$revision` to keep parents and children in sync by:
1. Using `$revision` to refer to the parent version from the child modules
2. Avoiding specifying a version in the child modules.

Fwiw, I don't see any logic conflict or disjoint between using CI-friendly (`$revision`) and `versions:set`.  But I'm probably missing something.  :--)

**Comment by ajarmoniuk** [comment]
So, did you try using set-property instead?

**Comment by CharlieReitzel** [comment]
I can play with it, manually.  But, as I said, my project has to work with a standard CI pipeline that forces `mvn versions:set -DnewVersion=N.x.0` with every merge to `main`.   

I have no problem with that scheme, either.  To my mind the "least surprise" implementation of `versions:set` on a project that uses `$revision` is to simply update the property value in the top level `pom.xml`.

**Comment by ajarmoniuk** [comment]
Please do file a feature request. 

The set goal you described is supposed to update the version of project with which it was invoked across the agregator, i.e. also update it where the project is used as parent or dependency.

If this does not occur then it's a bug, and might be caused by #799. Of course that would replace your property with a direct value, which is not what you want.

Regarding one remark – by "CI-friendly versions" I understand versions where the property is defined outside of the reactor, typically in the pipeline, e.g. by using the -Drevision switch. So it would not make sense to define a property in the project, which is then redefined in the pipeline anyway, hence my surprise.

So, unfortunately what you're looking for is not currently available with the set goal.
