### ISSUE TITLE
Inconsistency between dependency-updates and property-updates

### ISSUE THREAD

**Issue by javier-godoy** [mojohaus/versions#872]
Even if `allowSnapshots` is true, `display-dependency-updates` only detects newer dependencies up to the last release (even if there are newer snapshots), while `display-property-updates` is able to report the newer snapshots

For instance, if the "Snapshots" repository has com.example:foo:2.9.1-SNAPSHOT and 2.9.2-SNAPSHOT and the "Releases" repository has version 2.9.1, I get 
```
mvn versions:display-dependency-updates
[INFO] The following dependencies in Dependencies have newer versions:
[INFO]   com.example:foo .... 2.9.1-SNAPSHOT -> 2.9.1

mvn versions:display-property-updates
[INFO] The following version property updates are available:
[INFO]   ${com-example-foo.version} ......... 2.9.1-SNAPSHOT -> 2.9.2-SNAPSHOT
```

``` 
<repositories>
    <repository>
		<id>Releases</id>
		<url>https://example.com/releases</url>
	</repository>
	<repository>
		<id>Snapshots</id>
		<url>https://example.com/snapshots</url>
		<snapshots>
			<enabled>true</enabled>
		</snapshots>
		<releases>
			<enabled>false</enabled>
		</releases>
	</repository>
</repositories>

...

<dependency>
	<groupId>com.example</groupId>
	<artifactId>foo</artifactId>
	<version>${com-example-foo.version}</version>					
</dependency>

...
		
<plugin>
	<groupId>org.codehaus.mojo</groupId>
	<artifactId>versions-maven-plugin</artifactId>
	<version>2.14.1</version>
	<configuration>
		<allowSnapshots>true</allowSnapshots>
	</configuration>
</plugin>				
```

**Comment by ajarmoniuk** [comment]
Confirmed. The parameter is indeed ignored in VersionsHelper.lookupAvailableVersions.

**Comment by ajarmoniuk** [comment]
@slawekjaranowski looks like it's going to be a sizeable update. The reason is ArtifactVersions.includeSnapshots, which is used for reports, which is often assumed as true/false, depending on the mojo, and often forgotten. Also, method overloading with wrong assumptions about the default argument values.

So, I've cleaned it up a bit, removed `ArtifactVersions.includeSnapshots`, made `allowSnapshots` obligatory for `VersionsHelper.get...Updates` so that it's clear what we're getting every time. And for reports, made `allowSnapshots` an argument to the render method. Now it's clear what we're getting.

**Comment by ajarmoniuk** [comment]
@javier-godoy thanks for the report.

**Comment by slawekjaranowski** [comment]
If it looks as a bigger update, I would like to postpone after next bug fix release.

@ajarmoniuk  - You wrote, that you have done, so please create PR - we will see how big is.

**Comment by ajarmoniuk** [comment]
Yes, just doing all the needful checks first.
