### ISSUE TITLE
use-releases does not handle tens properly

### ISSUE THREAD

**Issue by joel-schaal** [mojohaus/versions#917]
I don't know if I have a particular setup on my side but if I do
```
$ mvn versions:use-releases -U -DallowRangeMatching=true -DprocessParent=true -DfailIfNotReplaced=true
```
I am getting a far bigger version than what I expect:
```
[INFO] Scanning for projects...
<...>
[INFO] --- versions-maven-plugin:2.14.2:use-releases (default-cli) @ commons-updater-repository ---
<...>
[INFO] Updated com.dentalwings.commons:versioninfo:jar:1.6-SNAPSHOT to version 1.69-76
```

I don't have the same result if I go through a property instead:
```
$ mvn versions:update-properties -U -Dincludes=com.dentalwings*:*:*:*:*-SNAPSHOT -DallowMajorUpdates=false -DallowMinorUpdates=false -DallowIncrementalUpdates=false
```
Here I get the result I would have expected from the `use-release` goal:
```
[INFO] Updated ${commons.version} from 1.6-SNAPSHOT to 1.6-93
```

**Comment by ajarmoniuk** [comment]
You compare `use-releases` with `update-properties` using different option sets. The options that you selected have different semantics, hence the results differ.

`allowRangeMatching=true` will select the highest found version where the version string **starts with** `1.6`. This includes `1.69-76`...

On the other hand, for `update-properties`, you selected `-DallowMajorUpdates=false -DallowMinorUpdates=false -DallowIncrementalUpdates=false` which will restrict the plugin **not** to update even the **minor** nor the incremental segment of the version. 

Because the **minor** segment happens to be `6`, and not `69`, it will **not** select the `1.69-76`.

So, I don't think this is a bug per se. I'd say that the meaning of `allowRangeMatching` might be a bit unfortunate, but it simply does what the documentation says -- matches the start of the version string.

**Comment by joel-schaal** [comment]
Ok, but how can I restrict `use-release` to behave the same as `update-properties` then (finding the latest release with the same major.minor) ? 
I'm also having difficulties understanding why those 2 goals don't share the same flags. Their mission is essentially the same, no ?

**Comment by ajarmoniuk** [comment]
Not really.

The thing is that those targets appeared evolutionally, and they don't necessarily share common options. The puprpose of `use-releases` is not finding the latest release, but simply stripping the `-SNAPSHOT` suffix from the version, with an additional option of using prefix search.

If you want to mimic the options you used for `update-properties`, you should use https://www.mojohaus.org/versions/versions-maven-plugin/use-latest-releases-mojo.html

**Comment by joel-schaal** [comment]
Thanks ! I tested `use-latest-releases` and it was exactly what I needed.


If I understand properly your last comment, if I have the version _1.6-SNAPSHOT_, `use-releases` will return:

> the highest version that starts with _1.6_ 

whereas on my side I understood that it would return:

> the highest version that starts with _1.6._ 

If I may add, the documentation about [`allowRangeMatching`](https://www.mojohaus.org/versions/versions-maven-plugin/use-releases-mojo.html#allowRangeMatching) could be clarified to better represent that behavior (maybe adding _1.11_ to the list of versions returned ?)

**Comment by ajarmoniuk** [comment]
>> If I understand properly your last comment, if I have the version 1.6-SNAPSHOT, use-releases will return:
>   the highest version that starts with 1.6

**Only** if you use the `-DallowRangeMatching=true`.

Otherwise it will attempt to simply strip the `-SNAPSHOT` suffix.

> If I may add, the documentation about [allowRangeMatching](https://www.mojohaus.org/versions/versions-maven-plugin/use-releases-mojo.html#allowRangeMatching) could be clarified to better represent that behavior (maybe adding 1.11 to the list of versions returned ?)

Good point.

**Comment by joel-schaal** [comment]
Since it was a misunderstanding from my part on the behaviour of [allowRangeMatching](https://www.mojohaus.org/versions/versions-maven-plugin/use-releases-mojo.html#allowRangeMatching), I will simply close that issue.
Thanks again for the quick and excellent feedback !
