### ISSUE TITLE
Can the ruleSet of the parent module be inherited?

### ISSUE THREAD

**Issue by diguage** [mojohaus/versions#943]
I configured the `ruleSet` in the parent BOM module. 

```xml
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>versions-maven-plugin</artifactId>
    <version>2.15.0</version>
    <configuration>
        <ruleSet>
            <ignoreVersions>
                <!-- Ignore Alpha's, Beta's, release candidates and milestones -->
                <ignoreVersion type="regex">(?i).*Alpha(?:-?\d+)?</ignoreVersion>
                <ignoreVersion type="regex">(?i).*SNATHOST(?:-?\d+)?</ignoreVersion>>
                <ignoreVersion type="regex">(?i).*Alpha*(?:-?\d+)?</ignoreVersion>
            </ignoreVersions>
        </ruleSet>
    </configuration>
</plugin>
```

I use the BOM as the parent of my project. And then, I run the command, it threw an error:

```bash
$ mvn versions:display-dependency-updates
#...
#...
#...
[ERROR] Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.15.0:display-dependency-updates (default-cli) on project mbt: Unable to parse configuration of mojo org.codehaus.mojo:versions-maven-plugin:2.15.0:display-dependency-updates for parameter ignoreVersion: Cannot find default setter in class org.codehaus.mojo.versions.model.IgnoreVersion -> [Help 1]

```

**Can the ruleSet of the parent module be inherited? And how to configure it?**

---

Maven version:

```bash
$ mvn -v
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-05T03:00:29+08:00)
Maven home: /path/to/maven/current
Java version: 1.8.0_362, vendor: Amazon.com Inc., runtime: /path/to/java/8.0.362-amzn/jre
Default locale: en_CN, platform encoding: UTF-8
OS name: "mac os x", version: "12.6", arch: "x86_64", family: "mac"
```

**Comment by ajarmoniuk** [comment]
1. You're using the `ruleSet` parameter wrong. When used with POM, the element *does not* conform to the rules XSD, but has its own schema. This is caused by the fact that it's a simplified version, using a model generated by Modello. Please see https://www.mojohaus.org/versions/versions-maven-plugin/version-rules.html for example usage.

In particular, `type` is a separate element and not an attribute of `ignoreVersion`. Again, please see the link I pasted above.

2. Regarding the question whether plugin configuration can be inherited -- that's a question about Maven rather than this plugin. See e.g. https://www.baeldung.com/maven-plugin-override-parent

**Comment by diguage** [comment]
> 1. You're using the `ruleSet` parameter wrong. When used with POM, the element _does not_ conform to the rules XSD, but has its own schema. This is caused by the fact that it's a simplified version, using a model generated by Modello. Please see https://www.mojohaus.org/versions/versions-maven-plugin/version-rules.html for example usage.

Thank you very much. It works well.
