### ISSUE TITLE
VersionDetails API takes a version parameter while it already has that information – refactoring needed

### ISSUE THREAD

**Issue by jarmoniuk** [mojohaus/versions#961]
While working on #960, I've noticed that the VersionDetails API needs refactoring. In many methods, a version string is required while it is already provided in the object on which the method is being executed. Otherwise the whole function is wrong, because it takes the versionComparator from this.

For example:

`VersionDetails.getNewerVersions(String version, boolean includeSnapshots)` requires a version string, but the same version string is already present as `this.currentVersion`.

other affected methods:
* `getNewerVersions(String version, Optional<Segment> upperBoundSegment, boolean includeSnapshots)`
* `getNewerVersions(String versionString, Optional<Segment> unchangedSegment, boolean includeSnapshots, boolean allowDowngrade)`
* `getNewestVersion(String versionString, Optional<Segment> upperBoundSegment, boolean includeSnapshots, boolean allowDowngrade)`
* `getNewestUpdateWithinSegment(ArtifactVersion currentVersion, Optional<Segment> updateScope, boolean includeSnapshots)`
* `getAllUpdates(ArtifactVersion currentVersion, Optional<Segment> updateScope, boolean includeSnapshots)`
* `getLowerBound(ArtifactVersion version, Optional<Segment> unchangedSegment)`

Additional test coverage is also needed.

**Comment by ajarmoniuk** [comment]
Will do that in a broader scope for >2.16.0.

**Comment by ajarmoniuk** [comment]
@cstamas, I've asked this question on the users.apache.org mailing list, but only got an answer that I should know the plugin's binary compatibility. Maybe I should ask you directly, if I may. 

My question is thus as follows: I see that Resolver has its own "world" of entities like e.g. [VersionRange](https://maven.apache.org/resolver/maven-resolver-api/apidocs/org/eclipse/aether/version/VersionRange.html) which is similar to Maven's [Restriction](https://maven.apache.org/ref/3.9.2/apidocs/org/apache/maven/artifact/versioning/Restriction.html).

My question is whether we should be moving towards the Resolver API with its classes or should we be rather using Maven objects seeing that we need to translate those every time that we want to use Resolver, or use some facade.

**Comment by cstamas** [comment]
Since Maven 3.1 (that had package change in resolver), it _is fully safe_ to use Resolver APIs directly, moreover, it IS recommended, as I personally consider maven-artifact _deprecated_ (with it's own broken version implementations and so on). So, to cover 3.1-3.999 range, moving off buggy Maven stuff and using Resolver bits are completely okay. Maven4 will introduce own API, BUT will remain Maven3 compatible (for plugins), hence, this above will still work.

Just pay attention to "behave well", as documented here https://maven.apache.org/resolver/api-compatibility.html and you should be fine.

One hint: maven-resolver-util must NOT be in provided scope, while the rest should, to bridge Maven 3.8-Maven 3.9 changes.

And sorry, did not spot this, was lost in my emails.

**Comment by jarmoniuk** [comment]
Thanks for that response. I think I have read your earlier replies regarding that and have already applied Resolver wherever feasible across this plugin when getting rid of the old maven-compat cruft here. Anyway, thanks. Took a long break cause reasons ;)
